### ISSUE TITLE
excludeGlobs

### ISSUE THREAD

**Issue by justinko** [rwx-research/captain#91]
Hello, Justin from Gifthealth here. 

This is a nice service! We use minitest and if we wanted to achieve the same functionality we'd have to spend the time incorporating the `parallel_tests` gem. Captain saved us a lot of work!

The issue I have is we run our Rails system tests in a separate Github action job so need to exclude them from our non-system partitioned tests. I checked out the captain source code and ultimately it's using `path#Match` which wouldn't allow us to exclude via `globs`. If you could add a `excludeGlobs` key that would be fantastic!

We currently use a glob like this:

```
- test/{foo,bar,car}/**/*_test.rb
```

And forgot to add an entire directory and was excluding 128 test files for a month ... whoops!

**Comment by TAGraves** [comment]
Thank you for the feedback! We just released v1.17.0 with support for negative globbing.

Now when you define globs, you can prepend an `!` to make the glob remove the matched files. The last glob that matches a file wins.

For example, if you had these files:
```
dir1/a.txt
dir1/b.txt
dir2/c.txt
```

and these globs:
```
- "*/*.txt"
- "!dir1/*.txt"
- "dir1/b.txt"
```

You would match `dir1/b.txt`, because it matches the third glob, and `dir2/c.txt`, because it matches the first glob and neither the second nor third globs match it, but you would not match `dir1/a.txt`, because it matches the second glob but not the third glob and the second glob is negated.
